name: flutter_wasm
version: 0.0.1
description: Flutter support for package:wasm
repository: https://github.com/dart-lang/wasm/tree/main/flutter_wasm
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  wasm:
    git:
      url: git@github.com:EntySquare/wasm.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.dart.flutter_wasm
        pluginClass: FlutterWasmPlugin
